<a href="https://colab.research.google.com/github/MaanasSM/Deep-Learning-Mini-Projects/blob/main/basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x= lambda a,b : a*b   # lambda input parameters : returned value
print(x(5,6))

30


In [ ]:
class myClass:
  x=5

In [ ]:
p1 = myClass()
print(p1.x)

5


In [ ]:
#intendation is important
class Person:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def myfunc(self):
    print("Hello my name is"+self.name)

p1=Person("John",36)
print(p1.name)
print(p1.age)
p1.myfunc()

John
36
Hello my name isJohn


In [ ]:
import numpy as np
a = np.array([1,2,3])
print("a= ",a)


a=  [1 2 3]


In [ ]:
b = np.array([(1,2,3),(4,5,6)], dtype=float)
print("b= ",b)


b=  [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
c= np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
print("c= ",c)

c=  [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [ ]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.ones((2,3,4),dtype=np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
d = np.arange(10,25,5)
print(d)

[10 15 20]


In [ ]:
# print(np.linspace(0,2,9))
print(np.linspace(0,2,9))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
e = np.full((2,2),7)
print(e)

[[7 7]
 [7 7]]


In [ ]:
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [ ]:
np.random.random((2,2)) #random numbers in 2x2 matrix
# np.random(2,2) #this wont work


array([[0.23083557, 0.79783468],
       [0.38017708, 0.47020772]])

In [ ]:
np.empty((3,2)) #random numbers in

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

In [ ]:
np.save('my_array',a) #normal saving file
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.savez('array.npz',a,b) # saving multiple things
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
np.load('my_array.npy') #loading everything

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
g = a-b
print(g)

[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
a+b


array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.add(a,b)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
np.divide(a,b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [ ]:
np.exp(b)

array([[  1096.63315843,   2980.95798704,   8103.08392758],
       [ 22026.46579481,  59874.1417152 , 162754.791419  ]])

In [ ]:
np.sqrt(b)

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [ ]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [ ]:
np.cos(b)

array([[ 0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396]])

In [ ]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [ ]:
e = np.array([[1,2],[1,2]])
f = np.array([[1,2],[1,2]])
e.dot(f)

array([[3, 6],
       [3, 6]])